name: CI

on:
  workflow_dispatch:
    inputs:     
      one:
        type: boolean
        description: One tag
        default: true
      two:
        type: boolean
        description: Two tag
        default: true
      three:
        type: boolean
        description: Three tag
jobs:
  test-feature:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     tags: [inputs.choice]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: yarn install
      - name: ${{inputs.one}} feature
        run: TAGS=@${{inputs.choice}} yarn run test-tag
      