name: On push job

on:
  push:
    branches:
      - GA_configs

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [one, two]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/install-deps
        with:
           npmAuthToken: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      - run: TAGS=@${{matrix.job}} npm run test-tag
      