name: CI

on:
  workflow_dispatch:
    inputs:
      boolean:
        type: boolean
        description: True or False
      choice:
        type: choice
        description: Make a choice
        options:
        - one
        - two
        - three
jobs:
  test-feature:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     tags: [inputs.choice]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: yarn install
      - name: ${{ inputs.choice }} feature
        run: TAGS=@${{ inputs.choice }} yarn run test-tag
      