name: CI

on:
  schedule:
    - cron: '*/4 * * * *'
  workflow_dispatch:
    inputs:
      test-feature-1:
        type: boolean
        description: Choose feature tag 1
        default: false
      test-feature-2:
        type: boolean
        description: Choose feature tag 2
        default: false
      test-feature-3:
        type: boolean
        description: Choose feature tag 3
        default: false
jobs:
  test-feature-1:
    if: ${{inputs.test-feature-1 == true}}
    uses: ./.github/workflows/reusable-test.yml
    with:
      test-tag: one

  test-feature-2:
    if: ${{inputs.test-feature-2 == true}}
    uses: ./.github/workflows/reusable-test.yml
    with:
      test-tag: two

  test-feature-3:
    if: ${{inputs.test-feature-3 == true}}
    uses: ./.github/workflows/reusable-test.yml
    with:
      test-tag: three
  