name: CI

on:
  workflow_dispatch:

jobs:
  test-feature:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [one, two]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
           npmAuthToken: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      - run: yarn install
      - run: TAGS=@${{matrix.job}} yarn run test-tag
      
