name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose test tags to trigger a feature
        options:
        - one
        - two
        - three

jobs:
  test-feature:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      tags: [inputs.choice]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: yarn install
      - run: TAGS=@${{matrix.tags}} yarn run test-tag
      