name: CI

on:
  pull_request:
  #schedule:
    #- cron: '*/1 * * * *'
  workflow_dispatch:
    inputs:
      test-feature-1:
        type: boolean
        description: Choose tag 1
        default: false
      test-feature-2:
        type: boolean
        description: Choose tag 2
        default: false
      test-feature-3:
        type: boolean
        description: Choose tag 3
        default: false
jobs:
  scheduled-tests:
    if: ${{ github.event_name == 'schedule' }}
    strategy:
      matrix:
        tags: [one, two, three]
      fail-fast: false
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
    with:
      test-tag: ${{matrix.tags}}
      event: ${{github.event_name}}
  
  test-feature-1:
    if: ${{inputs.test-feature-1 == true}}
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
    with:
      test-tag: one

  test-feature-2:
    if: ${{inputs.test-feature-2 == true}}
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
    with:
      test-tag: two

  test-feature-3:
    if: ${{inputs.test-feature-3 == true}}
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
    with:
      test-tag: three
    
  pr-test-event:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
    with:
      test-tag: one
  
