name: CI

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:
    inputs:
      test-feature-1:
        type: boolean
        description: Choose tag 1
        default: false
      test-feature-2:
        type: boolean
        description: Choose tag 2
        default: false
      test-feature-3:
        type: boolean
        description: Choose tag 3
        default: false
jobs:
  scheduled-tests:
    if: ${{ github.event_name == 'schedule' }}
    uses: ./.github/workflows/reusable-test.yml
    strategy:
      matrix:
        tags: [one, two, three]
      fail-fast: false
    with:
      ref: master
      test-tag: ${{matrix.tags}}
  
  test-feature-1:
    if: ${{inputs.test-feature-1 == true}}
    uses: ./.github/workflows/reusable-test.yml
    with:
      test-tag: one

  test-feature-2:
    if: ${{inputs.test-feature-2 == true}}
    uses: ./.github/workflows/reusable-test.yml
    with:
      test-tag: two

  test-feature-3:
    if: ${{inputs.test-feature-3 == true}}
    uses: ./.github/workflows/reusable-test.yml
    with:
      test-tag: three
  