name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose test tags to trigger a feature
        options:
        - one
        - two
        - three

jobs:
  test-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: yarn install
        with:
           npmAuthToken: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      - name: ${{inputs.choice}} feature
        run: TAGS=@${{inputs.choice}} yarn run test-tag
      