name: CI

on:
  workflow_dispatch:
    inputs:
      one:
        type: boolean
        description: one tag
      two:
        type: boolean
        description: two tag
      three:
        type: boolean
        description: three tag
jobs:
  test-feature:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     tags: [inputs.choice]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: yarn install
      - name: ${{ inputs.one }} feature
        run: TAGS=@${{ inputs.one }} yarn run test-tag
      