name: CI

on:
  workflow_dispatch:
    inputs:
      workflow:
        type: choice
        description: Choose an Editor feature tag
        options:
         - one
         - two
      workflow-2:
        type: choice
        description: Choose an Integration feature tag
        options:
         - two
         - three
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: yarn install

  test-feature-2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ${{ inputs.workflow }} feature
        run: TAGS=@${{ inputs.workflow }} yarn run test-tag

  test-feature-3:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ${{ inputs.workflow-2 }} feature
        run: TAGS=@${{ inputs.workflow-2 }} yarn run test-tag
  