name: On push job

on:
  workflow_dispatch:

jobs:
  {matrix.job}:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [one, two]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
           npmAuthToken: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      - run: npm install
      - run: TAGS=@${{matrix.job}} npm run test-tag
      
