name: PR event

on:
  pull_request:
    types:
      - labeled

jobs:
  test:
    if: ${{ github.event.label.name == 'run-tests' }}
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
      - run: TAGS=@one yarn run test-tag
