name: Reusable Integration and Regression test workflow

on:
  workflow_call:
    inputs:
      test-tag:
        type: string
        required: true
        description: Choose a test tag

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: TAGS=@${{inputs.test-tag}} yarn run test-tag
      