name: Reusable Integration and Regression test workflow

on:
  workflow_call:
    inputs:
      test-tag:
        type: string
        required: true
        description: Runs a test tag
      event:
        type: string
        required: false
        description: github event

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: development
    env:
      DEV_MESSAGE: ${{ secrets.DEV_MESSAGE }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{inputs.event}}
      - run: google-chrome --version
      - run: yarn install
        env:
          REPO_KEY: ${{ secrets.REPO_KEY }}
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
      - name: ${{inputs.test-tag}} feature
        run: TAGS=@${{inputs.test-tag}} yarn run test-tag
      - name: Report Status to Slack channel
        if: always() && inputs.event == 'schedule'
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: 'Regression test tag - "${{inputs.test-tag}}" has failed'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_AUTOMATION_TEST_WEBHOOK_URL }}
